# Generated by Django 4.0.3 on 2024-05-27 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0004_cliente_descuento_item_menu_pedido_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carta.categoria'),
        ),
    ]
