# Generated by Django 4.0.3 on 2024-05-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0005_alter_item_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, upload_to='items/', verbose_name='foto'),
        ),
    ]
