# Generated by Django 4.0.3 on 2024-05-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0006_item_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
