# Generated by Django 4.0.3 on 2024-05-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0008_pedidoitem_alter_pedido_items_pedidoitem_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='items',
            field=models.ManyToManyField(to='carta.item'),
        ),
    ]
