# Generated by Django 4.0.3 on 2024-05-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0009_alter_pedido_items'),
    ]

    operations = [
    ]
